### ISSUE TITLE
[BUG] - build probleem in polymer project

### ISSUE THREAD

**Issue by johanbuntinx** [milieuinfo/webcomponent-vl-ui-proza-message#41]
**Omschrijf het probleem**
Gebruik van webcomponent-vl-ui-proza-message geeft out of memory error

npm run build uitvoeren duurt erg lang (met constant 100% CPU en tot 1.8 GB memory) en geeft uiteindelijk
[INFO] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[polymerBuildOoM.txt](https://github.com/milieuinfo/webcomponent-vl-ui-proza-message/files/4381235/polymerBuildOoM.txt)

**Hoe te reproduceren**
voeg webcomponent-vl-ui-proza-message aan een project met polymer
import 'vl-ui-proza-message/dist/vl-proza-message.min.js'; 
npm run build 

`code snippet`

**Gewenst gedrag**

**Screenshots**
Indien mogelijk, voeg hier screenshots/logs/videos toe

**Omgeving (gelieve aan te vullen):**
 - Browser [vb. chrome, safari]
 - Versie [vb. 22]
 - Versie component [vb. 1.0.0]

**Extra info**
wanneer versie 5.2.1 van tinymce in de lib folder van proza wordt gezet ipv 5.1.5 werkt het wel

**Comment by driesva** [comment]
Is er eigenlijk een reden waarom tinymce mee gebundeld wordt?

**Comment by SanderKleykens** [comment]
> Is er eigenlijk een reden waarom tinymce mee gebundeld wordt?

@driesva dat komt omdat een custom build van TinyMCE nodig is. TinyMCE heeft problemen om correct te werken wanneer het 1 of meerdere shadow DOM's diep zit.

**Comment by kevcraey** [comment]
wordt opgepikt in https://www.milieuinfo.be/jira/browse/UIG-596

**Comment by SanderKleykens** [comment]
@johanbuntinx en @driesva de OOM is verholpen in vl-ui-proza-message v1.0.2.
Het verschil zit hem niet in de gebruikte versie van TinyMCE, maar in het type van minified js die we bundelen. Er worden verschillende versies gemaakt in de TinyMCE build.
