### ISSUE TITLE
[TASK] - Uitbreiden van documentatie rond communicatie met proza service

### ISSUE THREAD

**Issue by SanderKleykens** [milieuinfo/webcomponent-vl-ui-proza-message#49]
**Beschrijving**
Wij verwachten dat met proza te communiceren valt onder "proza/...", waarbij men nog een `<base>` tag kan gebruiken om dat relatieve pad te verleggen. Ik denk niet dat deze verwachting ergens beschreven staat. Ik zou dat op zijn minst ergens in de documentatie/demo zeggen en mogelijks zelfs een korte beschrijving van hoe dat kan met Spring Boot en Zuul.

**Comment by driesva** [comment]
Merk op dat Zuul in maintenance mode is. Idealiter wordt er naar Spring Cloud Gateway gekeken voor de toekomst.
