### ISSUE TITLE
Introductie event om dynamisch gegenereerde tekst volledig zichtbaar te maken in combinatie met vl-ui-wizard

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-proza-message#62]
**Wat moet er gebeuren**
Een updateCompleted event.

**Extra info**
Ik krijg layout issue als vl-proza-message will gebruiken met lit-element. 

De vl-proza-message maakt programmatically element wysiwyg aan. Dit element wordt niet gevlogt door lit-element. Daardoor moet ik manuele een resize event dispatch. 

Daar zou ik graag vl-proza-message een event kunnen gooien wanneer de opladen klaar is.

vb:
`  _loadMessage() {
    if (this._domain && this._code) {
      VlProzaMessage._getMessage(this._domain, this._code).then(message => {
        this._wysiwygElement.innerHTML = message;
        this.__wrapWysiwygElement();
        if (this.__containsBlockElement(message)) {
          this.setAttribute('data-vl-block', '');
          this.dispatchEvent(new CustomEvent('message-loaded'));
        }
      });
    } else {
      this._wysiwygElement.innerHTML = null;
      this.dispatchEvent(new CustomEvent('message-loaded'));
    }
  }`

Voor de resize:
<img width="1388" alt="Screenshot 2020-06-05 at 14 17 47" src="https://user-images.githubusercontent.com/51441000/84036920-2e018580-a99e-11ea-8c03-e1e391129266.png">

Na de resize:
<img width="1103" alt="Screenshot 2020-06-08 at 15 46 52" src="https://user-images.githubusercontent.com/51441000/84037865-78373680-a99f-11ea-90a6-c4efe2f6054d.png">

**Comment by coemans** [comment]
@ZhaodiFengVlaanderen doet het probleem zich nog voor op de #master van vl-ui-wizard na fix [van #19](https://github.com/milieuinfo/webcomponent-vl-ui-wizard/issues/19)?

**Comment by ZhaodiFengVlaanderen** [comment]
lijkt mij inderdaad opgelost in laatste versie van master.
