### ISSUE TITLE
[BUG] - Vulnerabilities in proza-client 

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-proza-message#63]
**Omschrijf het probleem**

1. De OWASP report vindt veel vulnerabilities in be.milieuinfo.proza/proza-client. Dit ging vooral over CXF-3.1.11

2. In de MANIFEST.MF van proza-client.jar zitten volgende:
`
Implementation-URL: http://projects.spring.io/spring-boot/acd-springbo
 ot-parent/proza/proza-client/
Implementation-Vendor: Pivotal Software, Inc.
`
Daardoor interpreteert OWASP proza-client ook als een spring project en markeert als een kwetsbare versie.

**Hoe te reproduceren**
Zoals https://www.milieuinfo.be/confluence/display/CONTERK/Security+-+OWASP+dependency+check . De OWASP check uitvoeren.

**Comment by kevcraey** [comment]
is dit front-end proza?

**Comment by ZhaodiFengVlaanderen** [comment]
> is dit front-end proza?

Nee, dit is back-end

**Comment by coemans** [comment]
Issue wordt gesloten aangezien het back-end is, zal verder afgehandeld worden via intern Jira ticket.
