### ISSUE TITLE
[BUG] - In Lit-html: proza-message zorgt de event-listener van andere webcomponent niet toegevoegd

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-proza-message#64]
**Omschrijf het probleem**
In Lit-html: als proza-message gecombineerd  met andere webcomponent, dan wordt de eventlistener van andere webcomponent niet toegevoegde.

**Hoe te reproduceren**
De 'click' event handler van button is niet toegevoegd.
```HTML
<div>
  <vl-alert type="warning" title='registratie.voorwaarden.meldingTitel'>
    <div>
     <vl-proza-message domain="ERKENNINGEN" code="registratie.voorwaarden.meldingTekst"></vl-proza-message>
    </div> 
  </vl-alert>
  <button id="button-test" type="button" is="vl-button"  @click="${this._toggleVolgende}">click</button>
  <p>De 'click' event van button werkt niet wanneer gecombineerd met een vl-proza-message</p>
</div>
```

Ik probeer dit te demonstreren via volgende repository:
https://github.com/milieuinfo/demo-proza-error-in-lit-element
U kunt dit start met 'npm run local'

**Comment by coemans** [comment]
@ZhaodiFengVlaanderen ik heb op basis van je voorbeeld een demo uitgewerkt, voorlopig zonder lit-html

```HTML
<div>
  <vl-alert type="warning" title='Titel'>
    <div>
      <vl-proza-message id="message-1" data-vl-domain="foo" data-vl-code="bar"></vl-proza-message>
    </div> 
  </vl-alert>
  <button type="button" is="vl-button">click</button>
  <p>De 'click' event van button werkt niet wanneer gecombineerd met een vl-proza-message</p>
</div>
<script>
  document.querySelector('button').addEventListener('click', () => console.log('click event captured'));
</script>
```

In dit voorbeeld werkt de click event listener. De button staat ter hoogte van de vl-alert, ik zie niet hoe de proza-massage de event listeners van de button zou kunnen beïnvloeden.

**Comment by ZhaodiFengVlaanderen** [comment]
> @ZhaodiFengVlaanderen ik heb op basis van je voorbeeld een demo uitgewerkt, voorlopig zonder lit-html
> 
> ```
> <div>
>   <vl-alert type="warning" title='Titel'>
>     <div>
>       <vl-proza-message id="message-1" data-vl-domain="foo" data-vl-code="bar"></vl-proza-message>
>     </div> 
>   </vl-alert>
>   <button type="button" is="vl-button">click</button>
>   <p>De 'click' event van button werkt niet wanneer gecombineerd met een vl-proza-message</p>
> </div>
> <script>
>   document.querySelector('button').addEventListener('click', () => console.log('click event captured'));
> </script>
> ```
> 
> In dit voorbeeld werkt de click event listener. De button staat ter hoogte van de vl-alert, ik zie niet hoe de proza-massage de event listeners van de button zou kunnen beïnvloeden.

programmatische werkt alles well, maar werkt niet als ik via de lit-literal  doet, dus  zoals `<button id="button-test" type="button" is="vl-button"  @click="${this._toggleVolgende}">click</button>` werkt niet.

**Comment by coemans** [comment]
In het code voorbeeld zie ik proza error's aangezien er geen back-end of mock voorzien werd. Geeft de implementatie in jullie applicatie ook console errors in de proza component? Vermoedelijk stopt de applicatie op die error en wordt daardoor het click event of eender welk statement daarna niet correct uitgevoerd.

**Comment by ZhaodiFengVlaanderen** [comment]
Er is well een mock in backend.

**Comment by coemans** [comment]
Applicatief waarschijnlijk, maar in dit code voorbeeld niet. Wanneer ik de button voor de proza-massage zet, lijkt het wel te werken wat de assumptie lijkt te bevestigen.

**Comment by coemans** [comment]
Na verder onderzoek wordt het probleem vermoedelijk veroorzaakt door lit-html achterliggend omdat er op constructie niveau een wysiwyg container element werd toegevoegd. @ZhaodiFengVlaanderen kan je eens testen met de branch van PR #76?
